DROP TABLE IF EXISTS price;

CREATE TABLE price (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	dates TEXT NOT NULL,
	open REAL(30) NOT NULL,
	high REAL(30) NOT NULL,
	low REAL(30) NOT NULL,
	close REAL(30) NOT NULL,
	adj_close REAL(30) NOT NULL,
	volume INTEGER(30) NOT NULL
)